# Generated by Django 5.2.3 on 2025-08-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='benefits',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='contact_email',
            field=models.EmailField(default='hr@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='job_type',
            field=models.CharField(default='Full-time', max_length=50),
        ),
        migrations.AddField(
            model_name='jobpost',
            name='salary_range',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='required_skills',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
